apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "jobManager.labels" . | nindent 4 }}
  name: trendmicro-job-manager
  namespace: {{ .Release.Namespace }}
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        checksum/auth: {{ include "container.security.auth.secret" . | sha256sum }}
{{- with (default .Values.podAnnotations.defaults .Values.podAnnotations.jobManager) }}
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "jobManager.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "jobManager.serviceAccountName" . }}
{{- $securityContextEnabled := .Values.securityContext.enabled }}
{{- $securityContext := default .Values.securityContext.default .Values.securityContext.jobManager }}
{{- $podSecurityContext := default .Values.securityContext.default.pod $securityContext.pod }}
{{- $containerSecurityContext := default .Values.securityContext.default.container $securityContext.container.jobManager }}
{{- if $securityContextEnabled }}
      securityContext:
{{ toYaml $podSecurityContext | indent 8 }}
{{- end }}
      {{- $imageDefaults := .Values.images.defaults }}
      {{- with .Values.images.jobManager }}
      {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
      {{- if not (eq "" $secret) }}
      imagePullSecrets:
        - name: {{ $secret | quote }}
      {{- end }}
      containers:
      - name: controller-manager
{{- if $securityContextEnabled }}
        securityContext:
{{ toYaml $containerSecurityContext | indent 12 }}
{{- end }}
        {{- $project := (default (default "trendmicrocloudone" $imageDefaults.project) .project) }}
        {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
        {{- $tag := (default $imageDefaults.tag .tag) }}
        image: {{ include "image.source" (dict "repository" $repository "registry" .registry "tag" $tag "imageDefaults" $imageDefaults "digest" .digest) }}
        imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
        {{- end }}
        args:
        - --cloud-one-endpoint={{ include "container.security.endpoint" . }}
        - --cloud-one-scan-job-image={{ .Values.jobManager.scanJobImage }}
        {{- with .Values.images.jobManager }}
        {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
        {{- if not (eq "" $secret) }}
        - --image-pull-secret-name={{ $secret }}
        {{- end }}
        {{- end }}
        - --excluded-namespaces
        {{- $excludeNS := (default (list) .Values.cloudOne.exclusion.namespaces) }}
        - {{ $excludeNS | join "," | quote }}
        command:
        - /app/job-manager
        env:
        {{- include "container.security.proxy.env" . | nindent 8 }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - mountPath: /secrets
            name: api-key
        resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.jobManager) | indent 12 }}
      volumes:
        - name: api-key
          secret:
            secretName: {{ template "container.security.fullname" . }}-auth
      terminationGracePeriodSeconds: 10
      nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.jobManager) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.jobManager) | indent 8 }}
      affinity:
{{ toYaml (default .Values.affinity.defaults .Values.affinity.jobManager) | indent 8 }}
{{- $classname := (default (default "" .Values.priorityClassName.default ) .Values.priorityClassName.jobManager) }}
{{- if not (eq "" $classname) }}
      priorityClassName: "{{ $classname }}"
{{- end }}
      restartPolicy: OnFailure

{{ if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jobManager.serviceAccountName" . }}
  labels:
    {{- include "jobManager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.jobManager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
